// Warning: generated file; your changes could be lost when a new file is generated.
#load @"load-references.fsx"
#load @"..\quick_start\ParallelSquare.fs"
      @"..\advanced_techniques\GenericTransform.fs"
      @"..\advanced_techniques\GenericMatrixMult.fs"
      @"..\profiling_and_performance_tuning\GenericMatrixTransp.fs"
      @"..\examples\device_query\DeviceQuery.fs"
      @"..\examples\basic\Basic.fs"
      @"..\examples\simple_scan\SimpleScan.fs"
      @"..\examples\matrix_transpose\MatrixTransp.fs"
      @"..\examples\matrix_multiplication\MatrixMult.fs"
      @"..\examples\generic_reduce\Plan.fs"
      @"..\examples\generic_reduce\Reduce.fs"
      @"..\examples\generic_reduce\Sum.fs"
      @"..\examples\generic_reduce\ScalarProd.fs"
      @"..\examples\generic_reduce\ReduceApi.fs"
      @"..\examples\generic_reduce\Test.fs"
      @"..\examples\generic_scan\Plan.fs"
      @"..\examples\generic_scan\Scan.fs"
      @"..\examples\generic_scan\Sum.fs"
      @"..\examples\generic_scan\ScanApi.fs"
      @"..\examples\generic_scan\Test.fs"
      @"..\examples\tridiag_solver\Solver.fs"
      @"..\examples\heat_pde\Solver.fs"
      @"..\examples\heat_pde\Direct3d.fs"
      @"..\examples\unbound\Reduce.fs"
      @"..\examples\unbound\Scan.fs"
      @"..\examples\unbound\MatrixMult.fs"
      @"..\examples\unbound\Random.fs"
      @"..\examples\cublas\Axpy.fs"
      @"..\examples\cublas\Gemm.fs"
      @"..\examples\cublas\GemmBatched.fs"
      @"..\Program.fs"
